### ISSUE TITLE
Links funktionieren nicht

### ISSUE THREAD

**Issue by adrian-jaques-b** [genderklage/genderklage#1]
Hallöchen :)

Ich hab eben eure Homepage durchstöbert und mir is aufgefallen dass in dem letzten Post auf der Startseite die Links nicht klickbar bzw. teilweise in einer "Wurst" geschrieben sind.
![Issue](https://user-images.githubusercontent.com/68905111/131794989-f7000bd5-7bb1-4aa5-a796-81a75f044242.PNG)
Mir selbst is das Thema sehr wichtig und ich dachte mir ich kann euch vlt. helfen diese Message zu verbreiten indem ich euch auf die nicht funktionierenden Links hinweise :) 

LG,
Jaqu

**Comment by genderklage-commits** [comment]
Hi Jaqu,

danke für dein Feedback, ich habe es an Venib weitergeleitet. Das Repo hier ist für die Genderklage, nicht für den Verein. Auf die Vereinshompage habe ich keinen Einfluss.

LG,
Pepper
